### ISSUE TITLE
Copy button visible before generating passwords

### ISSUE THREAD

**Issue by podfeet** [bartificer/xkpasswd-js#101]
A picture is worth a thousand words:

![IMG_1818](https://github.com/user-attachments/assets/054d75c5-7773-478e-9ed9-48d0445cdd71)

**Comment by podfeet** [comment]
I suspect this has something to do with the configuration settings, and I haven't looked at this for a while. Even if it's supposed to be there, it's not aligned correctly (squashed against the left edge), and it lets you copy when there's nothing to copy.

That big empty "Settings link" box is weird. no idea what I'm supposed to do with it. If I don't know, and I've been primary on the docs ...

**Comment by hepabolu** [comment]
The Settings link should be populated from the beginning, because the Default preset is already selected and has populated the settings. 
The link box is too long, therefore the copy link wraps on a small screen. It should be inline to the right of the link box.
