### ISSUE TITLE
Choosing 1 word always generates a password with 2 words

### ISSUE THREAD

**Issue by podfeet** [bartificer/xkpasswd-js#105]
Take any configuration and in settings change to 1 word, and the resulting password will have 2 words. Here’s the default config changed to 1 word:

https://beta.xkpasswd.net/?c=ZW5nbGlzaCwxLDQsOCxDQVBJVEFMSVNFLFJBTkRPTSxmQSxJVUFrSlY0bUtpMWZLejA2Zkg0X0x5NDcsMiwyLEZJWEVELDgsUkFORE9NLCxJVUFrSlY0bUtpMWZLejA2Zkg0X0x5NDcsMiwy

**Comment by bbusschots** [comment]
If memory serves, the base library requires at least 2, so the bug could be that 1 is allowed by the UI.

**Comment by hepabolu** [comment]
Fixed by changing the min value in the index.html. Added an extra test to check that in fact a configuration with 1 word is changed to 2 words.
