### ISSUE TITLE
UI issue with Specified Character

### ISSUE THREAD

**Issue by podfeet** [bartificer/xkpasswd-js#107]
When the user changes the Separator type to "Specified Character", the special characters are replaced by the pipe symbol. While it makes a certain amount of sense to offer one character as an example, the pipe is a confusing choice because it looks like your cursor is in that text box so the user starts to type but nothing happens because the Specified Character box is still selected.

![CleanShot 2024-10-01 at 16 11 14@2x](https://github.com/user-attachments/assets/c573a8ac-e7f2-4787-b461-8a2b7d4e2fd7)

I wouldn't mention this just because it happened to me, but I was showing my husband something in XKPasswd and he did exactly what I did. He changed it to Specified Character and then started typing and was confused why his typing didn't show up.

Options that would be better:

* No character at all (you'd have to mark it red because it would be mandatory)
* As is but use something more distinctive like an asterisk or octothorpe
* Make it a dropdown with the options listed (but the default is not the pipe)

All of these would be improved my making the focus shift to the Character text box when Specified Character is selected.

**Comment by hepabolu** [comment]
The easiest solution is to replace the character, so I chose that for now.
