### ISSUE TITLE
As a user I can load and save my preset

### ISSUE THREAD

**Issue by hepabolu** [bartificer/xkpasswd-js#14]
# Requirements

- there is a section on the website to load or save a preset
- when a preset is loaded the configuration section is updated with the values from the preset
- passwords are then generated according to this configuration
- the preset can be saved as a JSON file
- the structure of the JSON file is documented

# Note

- the JSON structure is identical to the structure of the old Perl version

**Comment by hepabolu** [comment]
Can people please add their configs so I can test the loading and saving.

**Comment by del-leehopper** [comment]
{
 "num_words": 4,
 "word_length_min": 4,
 "word_length_max": 6,
 "case_transform": "RANDOM",
 "separator_character": "RANDOM",
 "separator_alphabet": [
  ".",
  ",",
  "/",
  "\",
  "[",
  "]",
  "'",
  "#",
  "{",
  "}",
  "!",
  "£",
  "$",
  "%",
  "&",
  "*",
  ")",
  "("
 ],
 "padding_digits_before": 2,
 "padding_digits_after": 2,
 "padding_type": "NONE",
 "random_increment": "AUTO"
}

**Comment by hepabolu** [comment]
Feature is available. Any errors found should result in a new issue.
