### ISSUE TITLE
Text of the third line of a password is cut off

### ISSUE THREAD

**Issue by podfeet** [bartificer/xkpasswd-js#19]
Current system is a 13" MacBook Air screen resolution set to 1710 x 1112. Running Safari and I verified zoom level is at 0.

<img width="800" alt="image" src="https://github.com/bartificer/xkpasswd-js/assets/12651464/e93167b8-b729-4649-a6cd-611498f59b45">

**Comment by hepabolu** [comment]
Solution is probably to increase the textbox based on the number of passwords in the box

**Comment by podfeet** [comment]
pull request submitting fixing the problem.
