### ISSUE TITLE
Fix Flash of Unstyled Content

### ISSUE THREAD

**Issue by hepabolu** [bartificer/xkpasswd-js#25]
A flash of unstyled content (FOUC) is shown when the page first loads.

**Comment by podfeet** [comment]
I see the same thing with Taming the Terminal on GitHub pages...

**Comment by pricemi115** [comment]
dibs

**Comment by hepabolu** [comment]
The problem might be that the entire content (css, webfont, js) is bundled into one main.js file that is added to the header. If it's separated into the css and webfont to add to the header and js to the bottom of the body, the problem might be solved.

**Comment by pricemi115** [comment]
@hepabolu  - Didn't see your suggestion until after I created the PR. I went down an alternate route of just making the affected div's hidden by default and then programmatically making them visible when the DOM is ready. Seemed to do the trick.
