### ISSUE TITLE
New preset for temporary passwords

### ISSUE THREAD

**Issue by bbusschots** [bartificer/xkpasswd-js#31]
A long time supporter has requested the beta facilitate the following:

> I work for a hospital and use it for simple temporary passwords.
I had it set up to use 2x 4-letter words, first letter of each word capital, followed by 2 numbers and a symbol - meant to be easy to read and understand over the phone and immediately changed.

This is a sensible generic use-case, so I suggest it be facilitated with a new preset named something like 'phone-friendly temporary password'

**Comment by hepabolu** [comment]
@bbusschots I've added the preset, can you get back to the original requester and let him/her know it's implemented?
