### ISSUE TITLE
List Passwords Individually with Copy Link

### ISSUE THREAD

**Issue by westbaystars** [bartificer/xkpasswd-js#33]
Instead of having a `textarea` full of multiple passwords, list the passwords in a `ul` list, each with a `copy` button at the head (instead of the usual dot) so that single passwords can be copied.

This alleviates the need to reside the list box according to the number of passwords generated and allows for individual passwords to be copied with the push (or tap) of a button.

**Comment by pricemi115** [comment]
dibs

**Comment by hepabolu** [comment]
Thanks for joining in.

**Comment by hepabolu** [comment]
Issue is resolved with pull request #56
