### ISSUE TITLE
Long-term location for xkpasswd.net (GitHub Pages too slow)

### ISSUE THREAD

**Issue by podfeet** [bartificer/xkpasswd-js#39]
The GitHub pages are working great for a beta site, but like all things GitHub pages, it's slow to load so you see an un-CSSd version before the whole thing loads. 

GitHub pages works great for the PBS shownotes but the more complex content requires a proper server.

Obviously this is a long-term issue but I wanted it recorded.

**Comment by hepabolu** [comment]
This is not a GitHub Pages issue, but the way the page is built. I also have this in my local version. I already recorded this as #25.

I agree that the app might be better hosted somewhere else, but not because GitHub Pages is slow.
For now I'll mark this as duplicate of #25.

**Comment by hepabolu** [comment]
I'll close this issue. The work will be done based on issue #25
