### ISSUE TITLE
Copy Button to the right of PASSWORDS doesn't appear on smaller widths

### ISSUE THREAD

**Issue by podfeet** [bartificer/xkpasswd-js#48]
Another responsive design problem.

Wide screen:
<img width="735" alt="image" src="https://github.com/bartificer/xkpasswd-js/assets/12651464/8af4d150-bc9a-47c6-815f-7952a75f04d9">

Narrow screen without copy button:
<img width="585" alt="image" src="https://github.com/bartificer/xkpasswd-js/assets/12651464/248a793a-0a60-4da1-8529-14f7ec21fa80">

**Comment by podfeet** [comment]
I can work on this one if you want to assign it to me.

**Comment by pricemi115** [comment]
@podfeet and @hepabolu - I recommend rejecting closing this. The copy button didn’t do anything anyway
and I removed it as part of my PR that is up for review.
Now that the passwords will be in a HTML List each with their own copy button (that works), this copy button is not long for this world

**Comment by hepabolu** [comment]
Issue is no longer necessary because of #56. Thanks Mike
