### ISSUE TITLE
Graphic is in the wrong order

### ISSUE THREAD

**Issue by podfeet** [bartificer/xkpasswd-js#51]
Current HTML has several elements of the page set in specific order. As the graphic is order-4, with screen readers the graphic's alt tag is read out loud after the generate password section and before the password area.  Very confusing in this order.

I know it was done for SEO but it's not very logical to the VoiceOver user.

**Comment by podfeet** [comment]
Why has a VoiceOver issue been pushed out to a future release? Accessibility must be a high priority.

**Comment by hepabolu** [comment]
It’s been moved to 1.0 Release and I already fixed it
