### ISSUE TITLE
padding and separator types get confused on second generate

### ISSUE THREAD

**Issue by podfeet** [bartificer/xkpasswd-js#55]
Steps to reproduce:

* Refresh
* Open config and Settings
* Change Padding type to specified character
  * choose ^
* Generate - should see padding of ^^ on each end
* Now without refreshing, change padding type to "Use Separator character". Leave Type of Separator at random character
* Generate again
* Should still see ^^ as padding

It gets weirder.
* Now change separator type to Specified character, like "-"
* Padding type is still set to use separator character
* Generate
* padding is still ^^ and separator character is NOT "-"

**Comment by hepabolu** [comment]
I can confirm this.

**Comment by hepabolu** [comment]
@podfeet, @pricemi115 and @macLurker Before I merge this into main, could you test this code in branch `issue-55` ?

**Comment by podfeet** [comment]
not sure what happened - all I did was click on AppleID preset

![CleanShot 2024-03-09 at 13 55 24@2x](https://github.com/bartificer/xkpasswd-js/assets/12651464/37522cb5-ad32-4dbc-a316-985727c42722)

**Comment by podfeet** [comment]
same thing with all of the presets I tried

**Comment by hepabolu** [comment]
Fixed

**Comment by pricemi115** [comment]
I seem to be ok, @hepabolu 
and I have the function mentioned in @podfeet's comment.

![image](https://github.com/bartificer/xkpasswd-js/assets/5100303/251d7f50-484f-4391-a3c8-a393ac1e982b)

**Comment by podfeet** [comment]
Good thing this was such a well-documented issue 😜 - I was able to follow the tests described and confirm that the issue has been fixed.

**Comment by pricemi115** [comment]
@podfeet , is your branch history exactly what Helma has in the issue-55 branch? Did you do a merge or rebase when trying to get her code and had a merge contention go sideways?

![image](https://github.com/bartificer/xkpasswd-js/assets/5100303/c898e046-2352-4762-9fae-adc3c527d2ac)

**Comment by pricemi115** [comment]
@hepabolu - tried all of the presets and various custom settings.
Seemed to work as expected

**Comment by podfeet** [comment]
@pricemi115 she fixed the problem before you saw it I think. it's all good now.

**Comment by pricemi115** [comment]
Timing, as they say, is everything!!

**Comment by hepabolu** [comment]
Thanks guys. I'll merge the code to main and close this issue.
