### ISSUE TITLE
Extra and unhelpful screen reader elements

### ISSUE THREAD

**Issue by pricemi115** [bartificer/xkpasswd-js#63]
Director of Accessibility and UX, @podfeet , identified a couple of elements getting picked up by voice over/screen readers that should not be.

https://share.cleanshot.com/Smh9VHbQ

**Comment by pricemi115** [comment]
@podfeet and @hepabolu:
The offending items are label elements with the `class="visually-hidden"` attribute. According to the Bootstrap docs, this attribute will "Visually hide an element while still allowing it to be exposed to assistive technologies (such as screen readers)".

These items were added recently in:
Commit#f09a0edc8054818c1ca1fa021865c568b52f93a5
Commit#7063d21c5527338ba9de6135f8c41fd242b94c44

Since these labels are both hidden and undesirable for screen readers, it would seem best to just delete them?? Alternatively, one can add the `aria-hidden="true"` attribute to the hidden labels, but I do not see the benefit of that over deleting the items.

Thoughts/Comments?

**Comment by hepabolu** [comment]
I think I added them when my editor (PHPStorm) was complaining about input fields without labels and they were forgotten when we removed the textarea. So removing is the best option in my opinion.

BTW @pricemi115 If you add a commit as #<commit hash> (without the word Commit as prefix) GitHub will turn it into a link to the correct commit.
I took the liberty of changing your post.

**Comment by pricemi115** [comment]
I did not know that!! Thank you.

**Comment by podfeet** [comment]
Someone appears to have removed them - whoever did should close this issue?

**Comment by hepabolu** [comment]
They were removed due to 2 PRs.
