### ISSUE TITLE
Indent of copy buttons word wraps passwords on mobile

### ISSUE THREAD

**Issue by podfeet** [bartificer/xkpasswd-js#69]
I'm going to try to fix this.

![image](https://github.com/bartificer/xkpasswd-js/assets/12651464/67d33bb3-a9cd-4835-9ed3-89bfdc3a87b9)

**Comment by podfeet** [comment]
I give up. I tried everything I know to get rid of padding & margin on <ul> elements using CSS and nothing moves that copy button to the left. I know passwordList in the view should do something about this but I remain baffled how to use those files to control the HTML. Someone else will have to fix this.

**Comment by hepabolu** [comment]
I updated the code. The list items are now buttons with visible feedback when clicked. @podfeet  Please test `issue-69` branch before I merge it.

**Comment by podfeet** [comment]
Hmmm. I don't see an `issue-69` branch...

**Comment by pricemi115** [comment]
Looking forward to seeing Helma's change. 

@podfeet - the view class "injects" the html ![image](https://github.com/bartificer/xkpasswd-js/assets/5100303/831baca1-b6d3-4634-a3d3-8cbbae9b9220)

**Comment by podfeet** [comment]
Yeah, I found the `<li>` element in the view class but I absolutely do not follow how anything around it works. It's hard to even articulate how little I understand looking at this file.

**Comment by hepabolu** [comment]
@podfeet sorry, forgot to push. It's there now.

**Comment by pricemi115** [comment]
@hepabolu  - I like it. Works great.

**Comment by pricemi115** [comment]
Also @hepabolu - for these "one off" html elements like the password list and text area - where do you draw the line on what, if anything, should go into the cascading style sheet vs just having the attributes in the html source? In these cases are there benefits to one over the other? 

When it comes to the web development side of things, I am definitely in the "knows enough to be dangerous" camp 😉

**Comment by podfeet** [comment]
This fixes the indent issue. I wish I knew why this fixed it though and removing padding (or margin) on the `ul` did not. ¯\_(ツ)_/¯

 I can tell that the entire line gets selected when I tap but in a way that's more confusing. I still don't know that I've copied anything so now I think all I've done is select the entire line.

Can't we just do something simple like have the copy button turn into the solid black version of the icon when pressed?

**Comment by podfeet** [comment]
I just tried adding a `.removeClass` then an `.addClass` to the button when pushed to change it to a checkmark. Not sure why the removeClass doesn't actually remove the clipboard icon but it's still not the worst solution.

```
     for (const pwdIndex in passAndStats.passwords) {
        const btn = $(`#copyclip_${pwdIndex}`);
        if (btn && (btn.length > 0)) {
          btn[0].addEventListener('click', async ()=>{
            // eslint-disable-next-line max-len
            await navigator.clipboard.writeText(passAndStats.passwords[pwdIndex]);
            btn.removeClass('bi-clipboard');
            btn.addClass('bi-check');
          });
        }
      }
```

**Comment by pricemi115** [comment]
Not sure about that. or at least "as written". Perhaps if we changed the icon for only the most recently copied thing? So in you case, if I have 3 passwords and I copy each one, they would all have changed to check marks. Do we want that or as I copy one password, the icon for all others goes back to a checkbox?

**Comment by pricemi115** [comment]
or making the content of each list item being a button with the text of the password?? 🤷‍♂️
Trying this now.....

**Comment by pricemi115** [comment]
@helma - with the proposed change, I think you inadvertently broke the unregistering of events in fn __resetPasswordUI()
No more buttons.
```
    // Clear out existing events.
    const existingListItems = this.#passwordList.find('button');
    for (const item of existingListItems) {
      if (item.hasOwnProperty('removeEventListener')) {
        item.removeEventListener('click');
      }
    }
```

**Comment by pricemi115** [comment]
Well this took WAY longer than I anticipated !!
But this is basically @podfeet 's idea, but the check mark is only on the last selected/copied item.
I also switched from the "clipboard" (paste) icon to a real "copy" icon.

** Also - @podfeet , you seem to have been putting the icon (class) on the wrong object. You were manipulating the hyperlink ( "<a>" ), which is named "btn" though it is no longer a button, as opposed to the "<i>" object.

```
      // Add event handlers for the copy buttons
      // eslint-disable-next-line guard-for-in
      for (const pwdIndex in passAndStats.passwords) {
        const btn = $(`#copyclip_${pwdIndex}`);
        if (btn && (btn.length > 0)) {
          btn[0].addEventListener('click', async ()=>{
            // eslint-disable-next-line max-len
            await navigator.clipboard.writeText(passAndStats.passwords[pwdIndex]);

            // Manage icons
            // Get the <i> elements for the passwords.
            const existingListItems = this.#passwordList.find(`i`);
            for (const item of existingListItems) {
              // Determine the correct icon for the password list items.
              const desiredClass  = (pwdIndex !== item.id) ? 'bi-copy' : 'bi-check';
              const obsoleteClass = (pwdIndex !== item.id) ? 'bi-check' : 'bi-copy';

              // Get an array of classes for the list item.
              let classList = Object.values(item.classList);

              // Remove the "obsolete" class if necessary.
              if (classList.includes(obsoleteClass)) {
                classList =classList.filter((removeClass) => {
                  return removeClass !== obsoleteClass;
                });
              }

              // Appemd the desired class if necessary
              if (!classList.includes(desiredClass)) {
                classList.push(desiredClass);
              }

              // Update the class.
              item.className = classList.join(' ');
            }
          });
        }
      }
```

**Comment by podfeet** [comment]
I'm not seeing any changes to the copy buttons when clicked in my latest pull from Origin of #69. (and yes I restarted npm)

**Comment by podfeet** [comment]
I don't follow how you did it @pricemi115 but I like it!

**Comment by pricemi115** [comment]
Happy to chat and take this as a learning opportunity.....for both of us...
As they say, "the best way to learn is to teach" 🤣

**Comment by hepabolu** [comment]
> @helma - with the proposed change, I think you inadvertently broke the unregistering of events in fn __resetPasswordUI() No more buttons.
> 
> ```
>     // Clear out existing events.
>     const existingListItems = this.#passwordList.find('button');
>     for (const item of existingListItems) {
>       if (item.hasOwnProperty('removeEventListener')) {
>         item.removeEventListener('click');
>       }
>     }
> ```

Ouch.  Sorry

**Comment by hepabolu** [comment]
> Also @hepabolu - for these "one off" html elements like the password list and text area - where do you draw the line on what, if anything, should go into the cascading style sheet vs just having the attributes in the html source? In these cases are there benefits to one over the other?
> 
> When it comes to the web development side of things, I am definitely in the "knows enough to be dangerous" camp 😉

I just don’t like style attributes because multiple properties are harder to read and it’s an extra location where you look for css.

**Comment by podfeet** [comment]
@pricemi115 and I went through his solution and I love it!

**Comment by pricemi115** [comment]
> > @helma - with the proposed change, I think you inadvertently broke the unregistering of events in fn __resetPasswordUI() No more buttons.
> 
> > 
> 
> > ```
> 
> >     // Clear out existing events.
> 
> >     const existingListItems = this.#passwordList.find('button');
> 
> >     for (const item of existingListItems) {
> 
> >       if (item.hasOwnProperty('removeEventListener')) {
> 
> >         item.removeEventListener('click');
> 
> >       }
> 
> >     }
> 
> > ```
> 
> 
> 
> Ouch.  Sorry 

No worries. That's why we do (or should do) peer reviews 😉

**Comment by podfeet** [comment]
Should the automated tests have caught this? I must confess I've forgotten to run them the last few times I've messed in the JavaScript.

**Comment by hepabolu** [comment]
> Should the automated tests have caught this? I must confess I've forgotten to run them the last few times I've messed in the JavaScript.

If I had tests for this part they would. So far my attempts to add jest tests for these files have failed and I forgot to test the preset buttons by hand.

**Comment by pricemi115** [comment]
And even if there were tests for the view class, catching events being left behind would be a challenge...I suspect

**Comment by hepabolu** [comment]
I added an adjusted version of @pricemi115 's snippet. And pushed it to the `issue-69` branch. Please review @podfeet and @pricemi115. If it works, I can add it to the main branch.

**Comment by pricemi115** [comment]
I like the "adjusted version" and it works as expected. One question/comment: Is there any concern or issue with calling removeClass() where the class does not exist? And conversely, calling addClass() where the class already exists?

Also, I am not seeing the check mark as bold or very large on Safari and Firefox on macOS 14.4.

**Comment by podfeet** [comment]
Bart specifically taught us to use `removeClass()` before adding a class just in case so I don't think there's any problems introduced by using that technique.

The changes look good to me.

**Comment by hepabolu** [comment]
> I like the "adjusted version" and it works as expected. One question/comment: Is there any concern or issue with calling removeClass() where the class does not exist? And conversely, calling addClass() where the class already exists?

AFAICT it looks like the jQuery functions 'try' to remove/add classes, but the browser makes sure nothing happens when the class  doesn't exist or already exists. 

> Also, I am not seeing the check mark as bold or very large on Safari and Firefox on macOS 14.4.

I know, I've tried, but the size is fixed to 16x16 and the bold is also not very obvious. I guess that's due to the way the bootstrap icons are set up. Fontawesome offers their icons as a font which can then be resized, bolded and do all kinds of nifty things like overlaying them to create new icons.

**Comment by pricemi115** [comment]
Thanx for the follow up and explanation
