### ISSUE TITLE
Separator - Random Character - maxlength needs increasing

### ISSUE THREAD

**Issue by del-leehopper** [bartificer/xkpasswd-js#72]
https://github.com/bartificer/xkpasswd-js/blob/e63e88b73bacf7d87644a8dfd2bf345b19c41ca1/src/index.html#L205
```
<input name="separator_alphabet" id="separator_alphabet" class="form-control rounded-end"
    type="text" size="6" minlength="2" maxlength="6" value="" />
```

The maximum length is currently 6, which is quite small (much smaller than previously). 
Also the default config has 18 characters. This means if you run it with the default config (unedited) it works fine, but if you delete a character, you cannot run it again until you reduce this figure to 6.

Of course, you can edit the code in the browser and this will run perfectly fine, but defeats the point of having a maximum. e.g.
`minlength="2" maxlength="100"`

I would suggest a reasonable limit is 32 characters.

Likewise for:
`<input name="padding_alphabet" id="padding_alphabet" class="form-control rounded-end" type="text" size="6" minlength="2" maxlength="60" value="">`

**Comment by del-leehopper** [comment]
https://github.com/bartificer/xkpasswd-js/issues/81#issue-2212135087
![image](https://github.com/bartificer/xkpasswd-js/assets/78899539/50a3970f-b6b3-4d1e-a15a-d3087caea09e)

Image courtesy of @podfeet 😉

**Comment by hepabolu** [comment]
Max length of alphabet set to 20
