### ISSUE TITLE
Link to imported Config

### ISSUE THREAD

**Issue by podfeet** [bartificer/xkpasswd-js#76]
### Discussed in https://github.com/bartificer/xkpasswd-js/discussions/30

<div type='discussions-op-text'>

<sup>Originally posted by **Arguably-Nutcase** February  7, 2024</sup>
A Link to an already imported Config would be appreciated. Makes it possible for users to easily bookmark their preferred config.</div>

**Comment by hepabolu** [comment]
This feature is merged into the code
