### ISSUE TITLE
Temporary Password - bad idea, unalarming warning, warning stays up

### ISSUE THREAD

**Issue by podfeet** [bartificer/xkpasswd-js#78]
1. I'm very concerned about the temporary password introduced in Issue #31 .  I know people - they will use these passwords and not change them. I get that a long-time supporter wants it but if we get the config import thing working then they can have it and we don't advertise it as a prominent feature.
2. If it must stay in place, the warning should be flaming red, not happy baby blue. 
3. Also, the warning stays up after a different preset has been chosen.

**Comment by hepabolu** [comment]
@podfeet:
1. makes sense
2. already fixed
3. Odd. When I select another preset the color changes appropriately. Note that there are 3 presets with a warning: WEB16, NTLM and TEMPORARY. Did you perhaps switch to one of these three?

**Comment by podfeet** [comment]
I must have chosen one of those other two. Can't replicate it otherwise.
