### ISSUE TITLE
Import Config - upload button doesn't do anything

### ISSUE THREAD

**Issue by podfeet** [bartificer/xkpasswd-js#86]
Saved my config (from the old days) to a JSON file. Ran it through a JSON validator which fixed one problem.

I select Choose file, then choose my file, and then hit Upload but nothing happens.

<img width="486" alt="image" src="https://github.com/bartificer/xkpasswd-js/assets/12651464/c10df7a2-2745-4d86-91bc-51eb125724e6">

**Comment by del-leehopper** [comment]
@podfeet I experienced the same issue. Strangely, if you open the "Settings" section, then try again, it will import the config! Something with it needing to be the active window or something?

I'm just happy I can import the config now! Of course, this issue will need to be fixed too.

**Comment by podfeet** [comment]
Interesting. Once I have told it about the file, it stays there. Closing the popup and opening Settings and then asking to import config again doesn't change the behavior for me.

**Comment by podfeet** [comment]
They never import because the import button doesn't do anything, so no, they're not there in settings after I use close instead.

**Comment by hepabolu** [comment]
> Uploading my JSON file just in case that's the problem.
> 
> [myxkpasswd.json](https://github.com/bartificer/xkpasswd-js/files/15168456/myxkpasswd.json)

The content is not JSON but a Perl-like construct. 

I converted it to proper JSON and then it works:

```
{
 "padding_alphabet": ["!", "@", "$", "%", "^", "&", "*", "+", "=", ":", "~", "?"],
  "separator_alphabet": ["-", "+", "=", ".", "_", "|", "~"],
  "word_length_min": 4,
  "word_length_max": 4,
  "num_words": 2,
  "separator_character": ".",
  "padding_digits_before": 1,
  "padding_digits_after": 1,
  "padding_type": "FIXED",
  "padding_character": ".",
  "padding_characters_before": 1,
  "padding_characters_after": 1,
  "case_transform": "ALTERNATE"
}
```

**Comment by hepabolu** [comment]
In the current state of the main branch ( 93e892b92ff96973a1e44fa8d08de1920b28397c )
does the upload button automatically close the modal dialog. Any errors are shown in the settings accordion

**Comment by podfeet** [comment]
Upload works for me now 🎉
