### ISSUE TITLE
Min Length can be greater than Max Length

### ISSUE THREAD

**Issue by podfeet** [bartificer/xkpasswd-js#88]
I seem to only have value breaking things! Steps to reproduce:

* choose temporary password
* generate 3 passwords (not sure if this step is required)
* change min length to 5, leaving max length at 4
* No error is thrown
* Generate 3 passwords
* Appears to create passwords with 4 and 5 letters
<img width="730" alt="screenshot showing temporary preset with min length set to 5 but max length left at 4. generates usable passwords" src="https://github.com/bartificer/xkpasswd-js/assets/12651464/de69a707-576c-4451-bc2e-0e0cf7bc1778">

**Comment by hepabolu** [comment]
Yes, that’s done intentionally.

**Comment by podfeet** [comment]
explain?

**Comment by hepabolu** [comment]
Rather than requiring min and max to be in the correct order, the assumption is made that the intention was to be the other way around. So they are switched before the passwords are generated.

**Comment by podfeet** [comment]
ok.
