### ISSUE TITLE
Display Min and Max Password Length For Given Configuration

### ISSUE THREAD

**Issue by schellbell** [bartificer/xkpasswd-js#91]
In the original version, the minimum/maximum possible password lengths were shown given the configuration. Given many sites min/max character lengths for passwords this was extremely useful

**Comment by hepabolu** [comment]
I'll add this to the 1.0 release milestone, because it was a feature in the original version.

**Comment by hepabolu** [comment]
The calculation was already there, it was just not displayed in the statistics
