### ISSUE TITLE
Add URL-based preset selection

### ISSUE THREAD

**Issue by bbusschots** [bartificer/xkpasswd-js#93]
### Discussed in https://github.com/bartificer/xkpasswd-js/discussions/92

<div type='discussions-op-text'>

<sup>Originally posted by **sandrock** June 18, 2024</sup>
I am writing procedures and I would like to add some links that would load a specified preset. 

Something like `https://beta.xkpasswd.net/?preset=NTLM`

I can't find a way so I believe this is not implemented?</div>

**Comment by irsheep** [comment]
Implementing this on Pull request #109

**Comment by hepabolu** [comment]
PR is merged. Thanks so much.
