### ISSUE TITLE
Preset  Web16 can generate 17 (or more?) char passwords

### ISSUE THREAD

**Issue by jwilliams-shadowsoft** [bartificer/xkpasswd-js#96]
I hate using Web16, but there are still websites out there that have a maximum of 16 chars. (Update your systems, Costco!)

In the beta, some of the given passwords I got were > 16. 17, even 18 chars!

**Comment by westbaystars** [comment]
I calculate it ALWAYS generating 17 character passwords:

* No padding
* 2-digit number at the end (2 characters)
* 1 separator character between 4 entities (3 words and 1 number -- 3 characters)
* 3 words of 4 characters each alternating case (12 characters)

`2 + 3 + 12 == 17`

As bad as sites are that max out at 16 character passwords, this preset will fail every time.

I guess we need to reduce the number of digits to 1.

**Comment by hepabolu** [comment]
Good catch. I've reduced the 2 digit number to 1
