### ISSUE TITLE
WEB32 Creates Maximum of 31 Character Passwords

### ISSUE THREAD

**Issue by westbaystars** [bartificer/xkpasswd-js#98]
Similar to issue #96 creating passwords with too many characters, WEB32 maxes out at 31 characters when it should go up to 32.

Looking at the definition:

* 1 symbol on each side (2 characters)
* 2-digit numbers on each side (4 characters)
* 1 padding character between 6 entities (4 words and 2 numbers -- 5 characters)
* 4 words with minimum of 4 characters (16 characters)
* 4 words with maximum of 5 characters (20 characters)

That creates a range of password length to be between 27 and 31.

Making one of the numbers a 3-digit number will add more entropy than double padding the end with the same padding character.

Discussion?

**Comment by hepabolu** [comment]
Equally good catch. I've increase the final number to 3 digits, because that's probably more memorable.
